### ISSUE TITLE
[Usage] url for model zoo not available

### ISSUE THREAD

**Issue by hyoje42** [linzhiqiu/CLIP-FlanT5#1]
### Describe the issue

Many thanks for sharing your amazing work! 
However, I am unable to access the URL provided for the model zoo. It would be greatly appreciated if you could provide me with the url for model checkpoint.

Thanks in advance!

**Comment by linzhiqiu** [comment]
Thanks for spotting this error -- the previous links in README was now fixed. Please check out: https://github.com/linzhiqiu/CLIP-FlanT5/blob/master/docs/MODEL_ZOO.md

**Comment by hyoje42** [comment]
It works well. Many Thanks!
